### ISSUE TITLE
Duplicated Postgres?

### ISSUE THREAD

**Issue by OneCricketeer** [tech4242/docker-hadoop-hive-parquet#1]
Hello 👋

It would seem as though you have multiple postgres instances running. 

Ref - https://hub.docker.com/r/bde2020/hive-metastore-postgresql/dockerfile

The explicit `postgres` service isn't necessary

**Comment by OneCricketeer** [comment]
I guess, unless you really wanted to isolate Hue Database from Hive Database, but I still don't see a problem with using a single service for just this simple architecture.

**Comment by tech4242** [comment]
Hey @cricket007, 

thank you for your message. As you mentioned yourself I wanted to separate them (Hue & Hive) This architecture is simple but I thought of it as a baseline for a more complicated setup that you could (in theory) start building from here. And since Hue is "just" a Dashboard and has nothing to do with the metastore, I thought it makes sense to separate them. It makes life a little simpler from a customisation standpoint due to the low coupling of the services.

Given that, I feel inclined to close the issue even if it can be argued as you did that this kind of overcomplicates the setup.

I also tried to highlight this further in my Medium article in the architecture diagram of the docker composition: https://miro.medium.com/max/1150/1*X-TiP3PJPrkndqNxw88IgQ.png :)
